name: Deploy to Production

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hbdhrmapi:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.PRODUCTION_SERVER_IP }}
        username: ${{ secrets.PRODUCTION_SERVER_USER }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        envs: DOCKER_HUB_USERNAME, ENV_FILE_CONTENT # <-- PERUBAHAN 1: Tambahkan variabel di sini
        script: |
          # Pindah ke direktori aplikasi
          cd /root/hbdhrmapi
          
          # Hentikan container yang sedang berjalan
          docker compose down
          
          # (Opsional) Hapus container dan image lama untuk memastikan pembersihan total
          # Hati-hati menggunakan perintah ini jika ada container/image lain di server Anda
          docker rm -f $(docker ps -a -q) || true
          docker rmi -f $(docker images -q) || true
          
          # Tarik image terbaru dari Docker Hub
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hbdhrmapi:latest
          
          # Buat file .env di server dengan konten dari GitHub Secrets
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          
          # Jalankan docker compose dengan variabel DOCKER_HUB_USERNAME
          # <-- PERUBAHAN 2: Tambahkan variabel sebelum perintah docker compose
          DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} docker compose up -d --force-recreate --build
          
          # Jalankan migrasi database
          docker compose exec app php artisan migrate --force
          
          # Bersihkan cache Laravel
          docker compose exec app php artisan config:cache
          docker compose exec app php artisan route:cache
          # docker compose exec app php artisan view:cache
