name: Deploy to Production

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hbdhrmapi:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.PRODUCTION_SERVER_IP }}
        username: ${{ secrets.PRODUCTION_SERVER_USER }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          # Pindah ke direktori aplikasi
          cd /root/hbdhrmapi
          
          # Hentikan dan hapus container lama yang terkait dengan proyek ini
          docker compose down
          
          # Hapus image lama dan tidak terpakai (dangling images) dengan aman
          docker image prune -af
          
          # Tarik image terbaru dari Docker Hub
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hbdhrmapi:latest
          
          # Buat file .env di server dari GitHub Secrets
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          
          # Jalankan container dari image yang baru ditarik. Opsi --build dihapus karena tidak perlu.
          DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} docker compose up -d --force-recreate
          
          # --- LANGKAH KRUSIAL UNTUK MENGHINDARI TIMEOUT ---
          # Perbaiki izin akses folder agar Laravel bisa menulis log dan cache
          echo "Fixing permissions..."
          docker compose exec app chown -R www-data:www-data storage bootstrap/cache
          
          # Jalankan migrasi database
          echo "Running database migrations..."
          docker compose exec app php artisan migrate --force
          
          # Buat cache untuk optimasi
          echo "Optimizing application..."
          docker compose exec app php artisan config:cache
          docker compose exec app php artisan route:cache